### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by alessandroAM** [edap/ofxSpaceColonization#1]
Hello, I am unable to compile the sources. I am on VS2015, downloaded GLM 0.9.8.5 and besides several compile errors with it (maybe the sources where for very old GLM releases?), some headers are missing too (ofxmain.h, of3dPrimitives.h). Thanks for any help.

**Comment by edap** [comment]
Hello Alessandro, can you compile the examples in the openframeworks folder? for example, does one of the examples in examples/3d work?
Second question, can you provide the complete error log?

**Comment by alessandroAM** [comment]
Hey David hello, thanks for the quick response and kindness. Actually, I decided to go through the algorithm paper myself and build my own tree 'experiment' project :) Your work and notes were really an inspiration and I'd like to thank you very much. If it's possible I'd like to ask an information about your approach, since I'm considering alternate ways. You basically build a new segment (branch) everytime a leaf finds a branch point within a certain range. That's fine but this way you end up with n branches, all made of 1 segment (2 points), while in some screenshots (for example the wireframe one), main branches seem to be made of several connected segments, and only minor branches depart from it as new ones.
So I was wondering how you account for it. Hope this is understandable in my English (I'm Italian).
Cheers

**Comment by edap** [comment]
Hello Alessandro, feel free to contact me by email, I'm italian too and you can switch to italian if you want.
Anyway, yes, I'm creating a new branch whenever the previous branch does not find a leaf, id does not matter if it is the main branch or a child of it, the process does not change. I would suggest you the Daniel Shiffman's tutorial, it is really neat.
